# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9153bf10eea216b3233bbd9ca50cf03ff177c63b701c03c6b5597b70844e62b9d610c7cb07bc2e8fe5589cef53adf3cedf96027ad591fdc33f99e51cc050e2ca

test:
  secret_key_base: b092bd8f3b9479f6ee5b4e939be3ebd220b63284d07038871655c11e85cd75d2ec465d591ff15fd5137498a2ef50f652c5462c1e98853f987baa7e37b2568dab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
